version: '3' 

services:

  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - servers
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - servers

  broker:
    build:
      context: ./mqtt
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - servers

volumes:
  postgres_data:

networks:
  servers: